# Site settings
title: kady
description: > # this means to ignore newlines until "baseurl:"
  Just my portfolio ! , A personal website for the superhero ME !
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://abdelrahman-elkady.github.io/" # the base hostname & protocol for your site
port: 3000
# Build settings
markdown: kramdown

highlighter: pygments

# Assets
sass:
    sass_dir: assets/_sass

# Bower exclusion !
exclude:
  - "bower_components"
  - "bower.json"

# links info

twitter_account: abdo_kady
github_account:  abdelrahman-elkady
linkedin_account: abdelrahmanelkady
email: elkadyabdelrahman@gmail.com
googleplus_account: abdelrahmanelkadyongoogle
facebook_account: abdelrahman.heshamelkady
steam_account: abdelrahmanelkady
instagram_account: abdelrahman_elkady
stackoverflow_id: 3357910
