# Site settings
title: Your awesome title
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://localhost:3000/" # the base hostname & protocol for your site
port: 3000
# Build settings
markdown: kramdown

# Assets
sass:
    sass_dir: assets/_sass

# Bower exclusion !
exclude:
  - "bower_components"
  - "bower.json"

# links info

twitter_account: abdo_kady
github_account:  abdelrahman-elkady
linkedin_account: abdelrahmanelkady
email: elkadyabdelrahman@gmail.com
googleplus_account: abdelrahmanelkadyongoogle
